### PR TITLE
Hap to anglesharp

### PR DESCRIPTION
**Pull request by yetanotherchris**
- Anglesharp for MenuParser, TocParser
- MarkupConverter now uses HtmlSanitizer package (Anglesharp-based) for cleaning HTML.

### CODE REVIEW

**Comment by 304NotModified** [comment]
> MarkupConverter now uses HtmlSanitizer package

good choice! :)

**Comment by yetanotherchris** [comment]
@304NotModified Roadkill took tests from a Microsoft AJAX library, HtmlSanitizer took those tests from Roadkill, Roadkill now uses HtmlSanitizer - the circle of life! I need alternatives to Lucene.net if you know any (in file based)

**Comment by 304NotModified** [comment]
Why you need an alternative to lucene ? For .net core?

Ps I have contributed to both roadkill and htmlsanitizer O:)

**Comment by yetanotherchris** [comment]
@304NotModified For .net core yeh

**Comment by 304NotModified** [comment]
4.8 beta is .net Core compatible? http://code972.com/blog/2016/07/98-lucene-net-4-8-is-in-beta-and-we-need-your-help

**Comment by yetanotherchris** [comment]
It's 4.5 unfortunately:
https://www.myget.org/feed/lucene-net/package/nuget/Lucene.Net/4.8.0.685-beta

**Pull request merged**
