### PR TITLE
Tui editor

### PR DESCRIPTION
**Pull request by clone206**
Branched from v2.0. Includes tui-editor and dependencies via npm, and renames config files with base settings. Extends commonmark slightly, to include tables support and customizes ui. See readme for install instructions.

### CODE REVIEW

**Comment by yetanotherchris** [comment]
Can you try merging master in?

**Comment by clone206** [comment]
As in, merge tui-editor into master in my repo and then create a PR for clone206:master --> roadkillwiki:master?

**Comment by yetanotherchris** [comment]
> As in, merge tui-editor into master in my repo and then create a PR for clone206:master --> roadkillwiki:master?

You will need to merge roadkill master (the upstream) into your fork for the conflicting files to resolve

**Comment by clone206** [comment]
Ok, I'm on it.

**Comment by clone206** [comment]
Actually, since `v2.0` is a tag and not a branch, I can't create a pull request that way. As of now the only branch I can see upstream is `master`. Is it possible to create a new branch from `v2.0` on your side? Merging the `v2.0` tag into `tui-editor` locally will do nothing since that's what the branch was created from originally, though offhand I'm not sure if rebasing locally on my end and resubmitting a PR to master could accomplish what we're after.

**Comment by yetanotherchris** [comment]
I've created a version-2 branch now, if you rebase to that we can merge it in - or preferably create a branch called `tui-editor` on your remote, and we merge that branch in and create a release from the branch

**Comment by clone206** [comment]
Ok, done. Closing this request.

**Pull request closed without merging**
