### PR TITLE
allow class to img ( for reponsive behavior )

### PR DESCRIPTION
**Pull request by ctrl-alt-d**

### CODE REVIEW

**Comment by yetanotherchris** [comment]
@ctrl-alt-d were you able to run the unit tests?

**Comment by ctrl-alt-d** [comment]
Not for the last 4 pull requests.

El dc., 4 nov. 2015 , 22:40 Chris S. <notifications@github.com> va escriure:

**Comment by ctrl-alt-d** [comment]
Some message about an accent or something like this. Apologies, I have not
copy error message.

El dc., 4 nov. 2015 , 22:48 dani herrera (ctrl-alt-d) <ctrl.alt.d@gmail.com>
va escriure:

**Comment by ctrl-alt-d** [comment]
Here it is:
https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316

...
Expected string length 1335 but was 1333. Strings differ at index 310.
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3784>
Expected: "...-4f7c-aee4-28eb23e13dbd','2.0.300','{\r\n
"AllowedFileTypes..."
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3785>
But was: "...-4f7c-aee4-28eb23e13dbd','2.0.0','{\r\n "AllowedFileTypes":..."
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3786>
--------------------------------------------^
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3787>

<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3788>at
Roadkill.Tests.Unit.SqlExportBuilderTests.Should_Export_SiteConfiguration_And_Plugin_Settings()
in
C:\projects\roadkill\src\Roadkill.Tests\Unit\Export\SqlExportBuilderTests.cs:line
229
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3789>

<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3790>

<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3791>Tests
Not Run:
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3792>1)
Ignored :
Roadkill.Tests.Unit.CreoleParserTests.Links_With_Tilde_Should_Not_Be_Escaped
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3793>
Currently failing
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3794>2)
Ignored : Roadkill.Tests.Unit.HtmlHelperExtensionTests.DialogPartial_Should_
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3795>3)
Ignored :
Roadkill.Tests.Unit.HtmlHelperExtensionTests.DialogPartial2_Should_
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3796>4)
Ignored : Roadkill.Tests.Unit.HtmlHelperExtensionTests.DropDownBox1_Should
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3797>5)
Ignored : Roadkill.Tests.Unit.HtmlHelperExtensionTests.DropDownBox2_Should
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3798>6)
Ignored :
Roadkill.Tests.Unit.HtmlHelperExtensionTests.SiteSettingsNavigation_Should_
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3799>7)
Ignored : Roadkill.Tests.Unit.MarkupSanitizerTests.GenerateTestXmlFile
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3800>
This was use to generate the initial Whitelist XML file and isn't a test
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3801>8)
Ignored : Roadkill.Tests.Unit.MarkupSanitizerTests.UrlWithScriptInHref
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3802>9)
Ignored :
Roadkill.Tests.Unit.UrlHelperExtensionsTests.CssBundle_Should_Return_Expected_Html
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3803>10)
Ignored :
Roadkill.Tests.Unit.UrlHelperExtensionsTests.JsBundle_Should_Should_Return_Expected_Html
<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3804>

<https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3805>Command
exited with code 1


On 4 November 2015 at 22:49, dani herrera (ctrl-alt-d) <ctrl.alt.d@gmail.com

**Comment by ctrl-alt-d** [comment]
ok, I understand now what are you saying: to run tests before pull request.

On 5 November 2015 at 08:26, dani herrera (ctrl-alt-d) <ctrl.alt.d@gmail.com
> wrote:

> Here it is:
> https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316
>
> ...
> Expected string length 1335 but was 1333. Strings differ at index 310.
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3784>
> Expected: "...-4f7c-aee4-28eb23e13dbd','2.0.300','{\r\n
> "AllowedFileTypes..."
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3785>
> But was: "...-4f7c-aee4-28eb23e13dbd','2.0.0','{\r\n "AllowedFileTypes":..."
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3786>
> --------------------------------------------^
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3787>
>
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3788>at
> Roadkill.Tests.Unit.SqlExportBuilderTests.Should_Export_SiteConfiguration_And_Plugin_Settings()
> in
> C:\projects\roadkill\src\Roadkill.Tests\Unit\Export\SqlExportBuilderTests.cs:line
> 229
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3789>
>
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3790>
>
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3791>Tests
> Not Run:
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3792>1)
> Ignored :
> Roadkill.Tests.Unit.CreoleParserTests.Links_With_Tilde_Should_Not_Be_Escaped
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3793>
> Currently failing
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3794>2)
> Ignored : Roadkill.Tests.Unit.HtmlHelperExtensionTests.DialogPartial_Should_
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3795>3)
> Ignored :
> Roadkill.Tests.Unit.HtmlHelperExtensionTests.DialogPartial2_Should_
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3796>4)
> Ignored : Roadkill.Tests.Unit.HtmlHelperExtensionTests.DropDownBox1_Should
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3797>5)
> Ignored : Roadkill.Tests.Unit.HtmlHelperExtensionTests.DropDownBox2_Should
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3798>6)
> Ignored :
> Roadkill.Tests.Unit.HtmlHelperExtensionTests.SiteSettingsNavigation_Should_
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3799>7)
> Ignored : Roadkill.Tests.Unit.MarkupSanitizerTests.GenerateTestXmlFile
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3800>
> This was use to generate the initial Whitelist XML file and isn't a test
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3801>8)
> Ignored : Roadkill.Tests.Unit.MarkupSanitizerTests.UrlWithScriptInHref
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3802>9)
> Ignored :
> Roadkill.Tests.Unit.UrlHelperExtensionsTests.CssBundle_Should_Return_Expected_Html
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3803>10)
> Ignored :
> Roadkill.Tests.Unit.UrlHelperExtensionsTests.JsBundle_Should_Should_Return_Expected_Html
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3804>
>
>
> <https://ci.appveyor.com/project/yetanotherchris/roadkill/build/2.0.316#L3805>Command
> exited with code 1
>
>
> On 4 November 2015 at 22:49, dani herrera (ctrl-alt-d) <

**Pull request merged**
